// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAWOnV7BOH_lv3A4Uw-ZFtI5gPTtkwwF8',
    appId: '1:403226360658:web:your-web-app-id',
    messagingSenderId: '403226360658',
    projectId: 'iot-health-monitoring-b51a7',
    authDomain: 'iot-health-monitoring-b51a7.firebaseapp.com',
    databaseURL: 'https://iot-health-monitoring-b51a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-health-monitoring-b51a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAWOnV7BOH_lv3A4Uw-ZFtI5gPTtkwwF8',
    appId: '1:403226360658:android:ab7f76deadecd1687b588b',
    messagingSenderId: '403226360658',
    projectId: 'iot-health-monitoring-b51a7',
    databaseURL: 'https://iot-health-monitoring-b51a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-health-monitoring-b51a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAWOnV7BOH_lv3A4Uw-ZFtI5gPTtkwwF8',
    appId: '1:403226360658:ios:your-ios-app-id',
    messagingSenderId: '403226360658',
    projectId: 'iot-health-monitoring-b51a7',
    databaseURL: 'https://iot-health-monitoring-b51a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-health-monitoring-b51a7.firebasestorage.app',
    iosBundleId: 'com.example.healthMonitorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAWOnV7BOH_lv3A4Uw-ZFtI5gPTtkwwF8',
    appId: '1:403226360658:macos:your-macos-app-id',
    messagingSenderId: '403226360658',
    projectId: 'iot-health-monitoring-b51a7',
    databaseURL: 'https://iot-health-monitoring-b51a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-health-monitoring-b51a7.firebasestorage.app',
    iosBundleId: 'com.example.healthMonitorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAWOnV7BOH_lv3A4Uw-ZFtI5gPTtkwwF8',
    appId: '1:403226360658:windows:your-windows-app-id',
    messagingSenderId: '403226360658',
    projectId: 'iot-health-monitoring-b51a7',
    databaseURL: 'https://iot-health-monitoring-b51a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-health-monitoring-b51a7.firebasestorage.app',
  );
}
